name: 'Fetch weather data'
description: 'fetching data from weerlive.nl'

inputs:
  api-token:
    description: 'api token secret cannot be accessed from a composite action'
    required: true

runs:
  using: "composite"
  steps:
    - name: Fetch north data
      id: requestN
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://weerlive.nl/api/json-data-10min.php?key=${{ inputs.api-token }}&locatie=53.166874,6.301408'
        method: 'GET'

    - name: Fetch north west data
      id: requestNW
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://weerlive.nl/api/json-data-10min.php?key=${{ inputs.api-token }}&locatie=52.553754,4.822178'
        method: 'GET'

    - name: Fetch east data
      id: requestE
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://weerlive.nl/api/json-data-10min.php?key=${{ inputs.api-token }}&locatie=52.513494,6.533156'
        method: 'GET'

    - name: Fetch mid data
      id: requestM
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://weerlive.nl/api/json-data-10min.php?key=${{ inputs.api-token }}&locatie=52.080360,5.474725'
        method: 'GET'

    - name: Fetch south west data
      id: requestSW
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://weerlive.nl/api/json-data-10min.php?key=${{ inputs.api-token }}&locatie=51.800166,4.475967'
        method: 'GET'

    - name: Fetch south east data
      id: requestSE
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://weerlive.nl/api/json-data-10min.php?key=${{ inputs.api-token }}&locatie=51.439604,5.662535'
        method: 'GET'

    - name: Update data files
      shell: bash
      run: |
        echo '${{ steps.requestN.outputs.response }}' > api/north.json
        echo '${{ steps.requestNW.outputs.response }}' > api/north_west.json
        echo '${{ steps.requestM.outputs.response }}' > api/mid.json
        echo '${{ steps.requestE.outputs.response }}' > api/east.json
        echo '${{ steps.requestSW.outputs.response }}' > api/south_west.json
        echo '${{ steps.requestSE.outputs.response }}' > api/south_east.json
