#!/bin/bash

echo "Running pre-commit hook..."

./gradlew ktlintFormat --daemon

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "You can't commit directly to main branch"
  exit 1
fi

status=$?

[ $status -ne 0 ] && exit 1
exit 0

