name: Android Release

on:
  release:
    types: [ published ]
  workflow_dispatch:

concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  android-release:
    name: Android Release

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Decode Keystore
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" > watkanikaan.keystore.asc
          gpg -d --passphrase "${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}" --batch watkanikaan.keystore.asc > app/watkanikaan.keystore

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: build prod
        run: ./gradlew app:bundleRelease
        env:
          VERSION_CODE: ${{ github.run_number }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Build Artifacts
          path: app/build/outputs/

      - name: Create service_account.json
        run: |
          echo "${{ secrets.SERVICE_ACCOUNT_JSON }}" > service_account.json.asc
          gpg -d --batch service_account.json.asc > service_account.json

      - name: Upload Android Release to Play Store
        uses: r0adkll/upload-google-play@v1.0.17
        with:
          serviceAccountJsonPlainText: service_account.json
          packageName: nl.watkanikaan.app
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: production
          inAppUpdatePriority: 5
          userFraction: 1.0
          whatsNewDirectory: distribution/whatsnew
          mappingFile: app/build/outputs/mapping/release/mapping.txt
