name: "Fetch weather API updates and cache results"

on:
  push:
    branches:
      - master
  schedule:
#    - cron: "*/35 * * * *"
    - cron: "*/30 0-1,4-23 * * *" # Every 30 minutes, at 12:00 AM through 01:59 AM and 04:00 AM through 11:59 PM > 294 API calls for 7 regions
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fetch weather data
        shell: bash
        run: |
          curl -X POST -d {} https://weerlive.nl/api/json-data-10min.php?key=${{ secrets.API_KEY }}&locatie=Utrecht > weather_data.json
      - name: Commit changed file
        uses: EndBug/add-and-commit@v7
        with:
          add: 'weather_data.json'