name: Fetch weather API updates and cache results

on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/30 0-2,6-23 * * *"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: mkdir -p api

      - name: Fetch north data
        id: requestN
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://weerlive.nl/api/json-data-10min.php?key=${{ secrets.API_KEY }}&locatie=53.034325, 6.366893'
          method: 'GET'

      - name: Fetch north west data
        id: requestNW
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://weerlive.nl/api/json-data-10min.php?key=${{ secrets.API_KEY }}&locatie=52.553754, 4.822178'
          method: 'GET'

      - name: Fetch west data
        id: requestW
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://weerlive.nl/api/json-data-10min.php?key=${{ secrets.API_KEY }}&locatie=52.022828, 4.706352'
          method: 'GET'

      - name: Fetch mid data
        id: requestM
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://weerlive.nl/api/json-data-10min.php?key=${{ secrets.API_KEY }}&locatie=52.121877, 5.305695'
          method: 'GET'

      - name: Fetch east data
        id: requestE
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://weerlive.nl/api/json-data-10min.php?key=${{ secrets.API_KEY }}&locatie=52.314997, 6.209913'
          method: 'GET'

      - name: Fetch south west data
        id: requestSW
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://weerlive.nl/api/json-data-10min.php?key=${{ secrets.API_KEY }}&locatie=51.595863, 4.741467'
          method: 'GET'

      - name: Fetch south east data
        id: requestSE
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://weerlive.nl/api/json-data-10min.php?key=${{ secrets.API_KEY }}&locatie=51.308874, 5.749949'
          method: 'GET'

      - name: Update data files
        run: |
          echo '${{ steps.requestN.outputs.response }}' > north.json
          echo '${{ steps.requestNW.outputs.response }}' > north_west.json
          echo '${{ steps.requestW.outputs.response }}' > west.json
          echo '${{ steps.requestM.outputs.response }}' > mid.json
          echo '${{ steps.requestE.outputs.response }}' > east.json
          echo '${{ steps.requestSW.outputs.response }}' > south_west.json
          echo '${{ steps.requestSE.outputs.response }}' > south_east.json

      - name: Setup Pages
        uses: actions/configure-pages@v1

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './api'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
