name: "Fetch weather API updates and cache results"

on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Update weather data"
        with:
          api-key: ${{ env.API_KEY }}
        run: |
          curl -X POST -d {} https://weerlive.nl/api/json-data-10min.php?key=${{ inputs.api-key }}&locatie=Amsterdam
